### ISSUE TITLE
add support for older hardware with alternative SDL and OpenGL 1

### ISSUE THREAD

**Issue by coadde** [Neverball/neverball#107]
please add support for older hardware with Geforce 2,3,4,FX series and others older video card.
Add alternative SDL support, due SDL2 only support OpenGL 2 and onward.

**Comment by parasti** [comment]
I don't think this is accurate. SDL2 only uses OpenGL 2 as one of several backends for their 2D rendering module, which Neverball doesn't even use.

IIRC, Neverball itself requires OpenGL 1.5 as a minimum, which is fully implemented by Nvidia's legacy drivers for those cards (if they even exist anymore). That's a decision we made to be able to support OpenGL and OpenGL ES at the same time.

Personally I don't see Neverball ever going back to supporting those cards, that stuff is just too old. I'm closing this.

That said, if there's a problem with Neverball not running on a supported system, feel free to open an issue with a description of the problem.
