### ISSUE TITLE
Drop PhysicsFS (was: Failure building ball.sol)

### ISSUE THREAD

**Issue by ghost** [Neverball/neverball#109]
I'm getting this odd make error when building the latest git version of neverball from source.
It fails when compiling data/gui/ball.sol, though the previous sol files seem to have compiled successfully.
There are also warnings about missing materials, though the respective png files are there.
[log.txt](https://github.com/Neverball/neverball/files/56322/log.txt)

OS is Windows XP SP3 32 bit, and I'm building using MSYS2 with the following command 'CC=gcc PLATFORM=mingw make'

Just tried a native Linux build on Ubuntu 14.04, and it was successful.

**Comment by parasti** [comment]
*ball.sol* is a map that gets loaded for the ball selection UI. so it's not that important. If you don't care about it, you could just skip it with `make -o data/gui/ball.sol`. If you wanna figure out why it doesn't compile, this might (or might not) provide a clue:

    ./mapc.exe data/gui/ball.map data
    echo $?

**Comment by osconnoisseur** [comment]
It returns 127, as make points out. Error code 127 usually means "command not found", but I don't really see how that is relevant here. I'll try to investigate this further.

**Comment by parasti** [comment]
Having built Neverball a couple of times on Windows recently, I'm certain that this is related to PhysicsFS. As a workaround, the game can be compiled with the standard filesystem module. As of 272798568 this is now the default behavior.

I'll admit that I don't care for PhysicsFS and think it would be best if it was dropped as a dependency. ZIP filesystem support IS something that Neverball should retain, so some replacement code would need to be written. Let's repurpose this issue for that.

**Comment by ChallengeSY** [comment]
Interesting find... Looks like I will be falling back to the drawing board myself, though it might still be worth trying to learn how to build PhysicsFS myself.

**Comment by parasti** [comment]
5 years later...

Resolved by #208
