### ISSUE TITLE
Goal of solved levels is sometimes not open despite setting saying otherwise

### ISSUE THREAD

**Issue by Wuzzy2** [Neverball/neverball#113]
I found a bug in Neverball 1.6.0 on GNU/Linux.

Sometimes, the goal of solved levels isn't open if the level is solved and the special setting “open goal in finished levels” is activated. I have to go back to the levels menu and click on “Open” (even if this is already active), then Neverball will actually recognize it. I am only referring to playing single levels, _not_ to Challenge Mode.

This bug does not happen always, I have not yet figured out a pattern here, but I noticed it several times when playing, so I am pretty sure this bug exists.

I have one wild guess: Maybe it only happens to levels you have beaten right in the previous game. But don't trust me on that.

**Comment by ChallengeSY** [comment]
If I am not mistaken, if you have beaten a level for the first time, and you immediately replay it without going back to the level screen, then goals are still locked regardless of the 'Goal State in Completed Levels' setting.

**Comment by Wuzzy2** [comment]
Oh, that might be the reason. Should be fixed, because it is confusing and annoying and a contradiction of what the user specified before.

**Comment by parasti** [comment]
It was intentionally made that way. It was something to do with the idea that "restart" should always restart the level in the original state. Obviously some people will prefer it one way, some will prefer it another way, but it's not a bug.

**Comment by Wuzzy2** [comment]
> because it is confusing and annoying **and a contradiction of what the user specified before**.

To be clear: I, the user, explicitly said via the settings that the goal should be opened for solved levels. I solved the level, play it again yet the goal is still closed. 

That's a bug, not a matter of preference.

That I have to go back to the levels menu only to make the goal open is not obvious at all, that's a bad UI design, which would be solved if the bug is fixed.

**Comment by parasti** [comment]
It's not a bug because I consciously implemented that feature. You asked the game to play the level again. It loaded the level as it was, but you expected it to be different. Who's right? It's all just preference. Could it be made into a checkbox to let the player decide? Sure. Would that be an improvement? Sure. Will anyone step forward to implement it? I honestly don't know - and that's not a refusal. You're very welcome to do so.

**Comment by parasti** [comment]
If anyone cares, I think this the commit with the entire rationale: 11939dc4e508bc2d47ef005964d1a9416bf5834b.

**Comment by ChallengeSY** [comment]
Making it a config option is definitely fair game since it gives the player flexibility. If I do not mind getting lost in the "nebulae" of source code, I could test what little I know with a potential experiment.

As of this post, I am currently recovering from having filled in [Clockwork Beta](http://sites.google.com/site/csnevergalaxy/clockwork), making it a complete 25-level set.

**Comment by Wuzzy2** [comment]
> It's not a bug because I consciously implemented that feature. You asked the game to play the level again. It loaded the level as it was, but you expected it to be different. Who's right?

I am. You have not refuted the clear contradiction between user setting and reality. Also, from an user standpoint there is no semantic difference between “restarting the level directly” and “going back to the levels menu and play the same level”. Yet apparently Neverball thinks those two things are radically different.

The real problem here is that all your intentions here happen all in the invisible and are not obvious to the user at all. The “restart” button has a hidden, secret meaning. ;-) This is not a matter of preference, it is about poor communictation to the user.
An alternative fix would be to rename the option to “Goals in finished levels: open (except when you have restarted the level”. Honestly, this is awkward and I don't recommend this but that's what would need to be done to avoid lying to the user without changing the actual behaviour.

There are at least 2 possible ways to fix this:

* Change the behaviour
* Stop lying to the user (i.e. use correct wording, no more user confusion, etc.)

As for the checkbox: I don't know. Is this really needed? It might make things even more confusing, can you at least explain me what it is supposed to do and how and where exactly you want to implement it? And besides, is there even any serious interest in that?

**Comment by Wuzzy2** [comment]
Oh, I know, I know! I have a much better idea to tackle this issue which should hopefully work out for all:
When you have finished a level the first time, and the goal setting was set to “open”, show *two* restart buttons instead of one:

* “Restart with locked goal” (*your* preference)
* “Restart with open goal” (*my* preference)

Those two buttons should also be displayed for any subsequent restarts, until the user finally went to the menu or to the next level. If the level is started from the level list again, the setting is respected as usual.
If there are spacing issues, re-align the buttons in multiple lines.

I am unsure what should happen if the user presses the “R” button instead.

**Comment by fwp** [comment]
You know what? As much as I love short best-time records, if there was a time machine back to 2003 it might have been a better decision to always require the goal to be unlocked through coin-collecting. This would have made the game design more streamlined and, in doing so, would have avoided a whole lot of complications such as this one.

**Comment by parasti** [comment]
So, make `lock_goals 1` or whatever it's called the default and revert the original changes? Retrying a newly-completed level then keeps the goal locked - you asked for the same thing and the game gave it to you. By toggling it off, you explicitly tell the game you're not asking for the same thing. Intent communicated, second guessing averted?
