### ISSUE TITLE
Add “Back” button after goal, time-out or fall out

### ISSUE THREAD

**Issue by Wuzzy2** [Neverball/neverball#118]
If you finish a level or fail due to time-out or fall out, there should be an additional button labelled “Back” or “Return” (or whatever) for returning to the level menu, just for convenience.
If the space is too tight, it may make sense to place the button on an additional line.

**Comment by camthesaxman** [comment]
You can just press the Esc key during that phase, and it will go back to the level menu. The lack of an actual button makes that not obvious, though.
