### ISSUE TITLE
"neverball.exe has stopped working" on Windows 10

### ISSUE THREAD

**Issue by SuicSoft** [Neverball/neverball#127]
I downloaded the Neverball zip from the official website to my Windows 10 laptop and extracted it. When I launch `neverball.exe`, I get the error message "neverball.exe has stopped working"
<br>
![screenshot 101](https://cloud.githubusercontent.com/assets/13938848/17393059/d072b05e-5a3e-11e6-92c6-00e02a1e60f8.png)

**Comment by ChallengeSY** [comment]
Your laptop might not support stencil buffer, which is easily the biggest performance killer. Look for _neverballrc_ in **Documents/My Games/Neverball**. If that file does not exist, just create it and then type:
`reflection 0`

I look forward to seeing if this works out.

**Comment by SuicSoft** [comment]
I created a file called "neverballrc" with the text `reflection 0` in the Neverball folder, `neverball-1.6.0`, but the problem is still there.

**Comment by parasti** [comment]
Your made-in-2007 laptop is running Windows 10? That sounds like it shouldn't even be possible. This needs input from people running Windows 10 on regular PC hardware.

**Comment by ChallengeSY** [comment]
Unfortunately, I am unable to reproduce the crash on my Windows 10 desktop. Diagnosing this problem will likely be difficult.

**Comment by SuicSoft** [comment]
> Your made-in-2007 laptop is running Windows 10? That sounds like it shouldn't even be possible.

My laptop runs Windows 10 smoothly, but does have some difficulty on 3D games. Not much. My other 2012 laptop runs Elementary OS so I can't check whether I get the issue on that computer.

**Comment by Xendon37** [comment]
i'm having the same error on my windows 7 dell inspiron 531s. could it be because we are both not using the default os?

**Comment by SuicSoft** [comment]
@Xendon37 That could be it, my laptop came with Windows Vista but I upgraded it to the Windows 10 Insider Preview

**Comment by camthesaxman** [comment]
I am actually able to run Neverball 1.6.0 with reflections enabled on an old computer from 2001 (Dell Dimension 4300 running Windows XP) with a graphics card from 2004 (ATI Radeon 9550xl), so I doubt that age of the hardware is an issue.

It could be that your laptop has a very low-end graphics card or your drivers are out of date. I also have a 2008 EeePC with very low-end Intel i915 graphics that only supports OpenGL 1.4, so enabling reflections causes it to crash on that machine.

I think a good solution would be to actually check whether `SDL_GL_GetProcAddress` in glext.c actually returned a valid pointer and log a warning if it didn't. https://github.com/Neverball/neverball/blob/master/share/glext.c#L127

**Comment by ersohnstyne** [comment]
The biggest performance killer is reflection. In the event that the game doesn't even run:

- Set reflection 0 in the neverballrc file.
- Set shadow 0 in the neverballrc file.

If your video board has less than 16MB of VRAM, set Textures to Low in the Options, or textures 2 in the neverballrc. This will eliminate texture thrashing.

If you have many problems on you laptop, you need:
- an special PG Gaming
- an GTX 970 or higher

**Comment by parasti** [comment]
@rlk You also wrote most of the text in their reply, which is a copy paste from the old Neverball FAQ.
