### ISSUE TITLE
[Feature Request] make install

### ISSUE THREAD

**Issue by DataDrake** [Neverball/neverball#128]
It would make packaging a lot easier for neverball if there were a make install rule.

**Comment by parasti** [comment]
It would also make Makefile maintenance harder for us, by an equal amount times distribution differences.

**Comment by DoctorWho11** [comment]
I like to point out that in a static makefile that maintenance wouldn't be hard. Your explanation at best I would call pure laziness.

**Comment by rlk** [comment]
To the contrary, we have no way of knowing which distribution a "make install" should target, so we have no idea where to target the installation. The Neverball developers are an upstream source, and as such we are platform agnostic. It is the problem of downstream packagers to decide where the binary should reside.

**Comment by ChallengeSY** [comment]
Given my personal experiences working with a custom fork, I believe it is tricky to get working builds anyway. I have personally compiled a build from within the Windows environment, but there were a few libraries I could not get working, so I was forced to forgo them.

In the past, I had no problem compiling a build in Ubuntu with all standard libraries enabled.

**Comment by DoctorWho11** [comment]
Most makefiles usually have an overriding parameter so if someone use make PREFIX=/usr it'll go there which makes it nicer for when someone uses make PREFIX=/usr DESTDIR=blahfolder it works for those who are packagers for distributions. So I still kinda stick to what I said.

**Comment by Justinzobel** [comment]
That's where configure comes in, it tells your make file where to install, prefix=/usr datadir=/etc for instance.

**Comment by DataDrake** [comment]
#129 Should sort this for 99% of linux systems. Cheers!
