### ISSUE TITLE
Can't build under Windows 10...

### ISSUE THREAD

**Issue by acterhd** [Neverball/neverball#131]
I tried Cygwin, but not helping with PhysFS. Need or neverball for Visual Studio or Linux. With Windows no more possible to build neverball. Cygwin (probably) supports packages only from installer. I beg or port to Visual Studio 2015, or include all libraries (problematic with PhysFS) with neverball source code. 

ALso new error (after fix PhysFS): 
```
share/lang.o:lang.c:(.text+0x52): undefined reference to `libintl_setlocale'
share/lang.o:lang.c:(.text+0x52): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_setlocale'
share/lang.o:lang.c:(.text+0x6c): undefined reference to `libintl_setlocale'
share/lang.o:lang.c:(.text+0x6c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_setlocale'
share/lang.o:lang.c:(.text+0xa2): undefined reference to `libintl_bindtextdomain'
share/lang.o:lang.c:(.text+0xa2): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_bindtextdomain'
share/lang.o:lang.c:(.text+0xb1): undefined reference to `libintl_bind_textdomain_codeset'
share/lang.o:lang.c:(.text+0xb1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_bind_textdomain_codeset'
share/lang.o:lang.c:(.text+0xb9): undefined reference to `libintl_textdomain'
share/lang.o:lang.c:(.text+0xb9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_textdomain'
share/lang.o:lang.c:(.text+0x1ca): undefined reference to `libintl_gettext'
share/lang.o:lang.c:(.text+0x1ca): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
share/st_common.o:st_common.c:(.text+0x5c8): undefined reference to `libintl_gettext'
share/st_common.o:st_common.c:(.text+0x5c8): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
share/st_common.o:st_common.c:(.text+0x630): undefined reference to `libintl_gettext'
share/st_common.o:st_common.c:(.text+0x630): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
share/st_common.o:st_common.c:(.text+0xbc3): undefined reference to `libintl_gettext'
share/st_common.o:st_common.c:(.text+0xbc3): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
share/st_common.o:st_common.c:(.text+0xc6a): undefined reference to `libintl_gettext'
share/st_common.o:st_common.c:(.text+0xc6a): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
share/st_common.o:st_common.c:(.text+0xdc1): more undefined references to `libintl_gettext' follow
share/st_common.o:st_common.c:(.text+0xdc1): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
make: *** [Makefile:433: neverball] Error 1
```

**Comment by parasti** [comment]
Please read the doc/install.txt file. Localization support requires libintl on Windows. Alternatively, you can disable localization:

```
make clean
make ENABLE_NLS=0
```

**Comment by ChallengeSY** [comment]
**libintl** itself seems to be a pain to install. I have a feeling that I may have accidentally broken my MinGW installation fooling around with **libintl**.

Also, it appears that **libintl**, **libiconv**, and **gettext** are strongly related. A partial compliment will not do.

**Comment by acterhd** [comment]
Yep. Need Visual Studio port...

**Comment by parasti** [comment]
Ultimately this is a support request on building from source, which I am sadly unable to help you with at this time. I recommend you visit http://neverball.org and find the link to our Steam group, perhaps somebody will be able to help you there. As is, I'm closing this as I have no reason to believe our build system has stopped working on supported systems.

**Comment by acterhd** [comment]
Also, I have question... How I can include C++ code in neverball?

**Comment by acterhd** [comment]
I builded neverball in Visual Studio 2015, but maps not loading.

**Comment by ChallengeSY** [comment]
You must compile the **map** files into **sol** files using **mapc**. You can use a single line in Command Prompt to do all the work, but this will likely take several minutes.

`for /R &m in (*.map) do mapc %m data`

**Comment by acterhd** [comment]
Also, I tried to convert to C++ and mouse control not locking. Game
running, but cursor locking not works.
