### ISSUE TITLE
Wiimote support outdated

### ISSUE THREAD

**Issue by parkerlreed** [Neverball/neverball#133]
It seems Neverball requires libwiimote/libcwiimote to be able to integrate with the Wiimote controller.

The last update to libwiimote was 2007 and when trying to build it now, fails miserably when trying to find the Bluetooth libraries it expects. 

Cwiid is available as an up to date library and even comes in most standard repos. Not sure if that would work for Neverball integration but would be great to have.

Funnily enough Neverball still throws my Bluetooth adapter into scanning (on 1.60) but obviously wasn't built with Wiimote support so it never connects. The config file still populated the wiimote_addr line.

**Comment by qwertychouskie** [comment]
Well, Cwiid was last updated in 2010... Best bet is https://github.com/rpavlik/wiiuse

**Comment by camthesaxman** [comment]
What OS and version are you using? I was able to build Neverball with Wiimote support on my Raspberry Pi running Raspbian Jessie, so those libraries should be available for modern Linux distros. I don't know about Windows, though.

**Comment by parkerlreed** [comment]
Arch Linux. Makes sense for Debian as it goes for stable... I may try Neverball again and see if something changed in the meantime.

**Comment by parasti** [comment]
Possibly resolved by `make ENABLE_TILT=wiiuse`, a Wiimote backend that uses the Wiiuse library.

**Comment by hendursaga** [comment]
@parasti yes, I would consider this resolved - I just built from source the latest wiiuse release and was immediately able to play with my Wiimote on Debian Stable.

**Comment by parasti** [comment]
Great, thanks for letting us know. I'm closing this then.
