### ISSUE TITLE
GNOME/Nautilus: Icon too big

### ISSUE THREAD

**Issue by rugk** [Neverball/neverball#138]
When you go to `/usr/share/applications` in Nautilus you'll see that the icons of Neverball & Neverput are 
too big in contrast to all other icons:

![icontoobig](https://cloud.githubusercontent.com/assets/11966684/21587898/7d000eac-d0e1-11e6-8708-b25152ab1803.png)

Neverball v1.6.0-3+b2 from Debian repos
Neverputt v1.6.0-3+b2 from Debian repos

**Comment by qwertychouskie** [comment]
According to the FreeDesktop specs, Neverball should provide a 48x48 icon, see https://github.com/supertuxkart/stk-code/issues/2718

**Comment by parasti** [comment]
This is a downstream issue. We provide all standard icon sizes, it's up to the distro to install them.
