### ISSUE TITLE
Vulkan API support?

### ISSUE THREAD

**Issue by capitalknew** [Neverball/neverball#147]
Hello. Will for Neverball Vulkan API support? I will wait this event....

**Comment by rlk** [comment]
I'm afraid this is incredibly unlikely. Neverball has been in maintenance mode for a number of years now, and there's not likely to be any core work on the engine done. Neverball was originally written against OpenGL 1.0 (it originally ran on SGI IRIX!) and the engine is exceedingly simple. It will not benefit at all from the lesser driver overhead that Vulkan provides. There's just no upside to the port.

**Comment by capitalknew** [comment]
Well, I'm betting that in FPS this gives 0 increments. But the main Zimes - in the purity and transparency of the code, and the rise of prestige among graphics developers.

**Comment by rlk** [comment]
That's just silly. Prestige among developers is a juvenile motivation.

Even if we were motivated by perceived status, jumping from one API to the next is not the way to earn it. It's just a good way to introduce unnecessary new bugs. A clean, solid, well-tested, mature code base is the only basis for regard that matters. We have that. Vulkan buys us nothing except problems we've already solved.

**Comment by capitalknew** [comment]
Yes, I apologize - I said something a bit wrong, I overdid the stick.

**Comment by qwertychouskie** [comment]
Should this be closed since it has been decided against?

**Comment by rlk** [comment]
@qwertychouskie yes I think so.
