### ISSUE TITLE
Results for Challenge Mode failures (NeverTrac #136)

### ISSUE THREAD

**Issue by Cheeseness** [Neverball/neverball#16]
This issue has been migrated from the Neverball Trac ticket list.

Instead of giving a "Game Over", why shouldn't the game give a window that says "Challenge Failed" and lists the final score and level reached.

Also, the "Game Over" button (when you lose your last life in Challenge Mode) should be replaced with something more appropriate (like "Continue") if you do this enhancement.

Original ticket created by @ChallengeSY

**Comment by ChallengeSY** [comment]
After several months of contemplation, I have decided to close my own idea for the time being.

I might still attempt it sometime down the road whenever I want a new challenge, but not now.
