### ISSUE TITLE
handle_key_up resets motion axis even if other key on axis is down

### ISSUE THREAD

**Issue by afontenot** [Neverball/neverball#163]
Suppose I press the right arrow key. The X0 axis gets set to 1.0. Now suppose I need to make a quick change to the left and press down the left arrow key before I've released the right arrow key. The new key_down sets the X0 axis to -1.0 as expected. Now, an instant later, I release the right arrow key (while the left arrow key is still down). The key_up now sets the X0 axis to 0.0. This resets the surface and to continue accelerating left I need to release the left arrow key and press it again. 

It looks to me like the best solution would be recording which is the last key to key_down, and ignoring key_up events on that axis unless it's from that key. But I'm not 100% sure of the best way to achieve this on this code base, so I haven't submitted a pull request.

**Comment by fwp** [comment]
Weird, for some reason I was under the impression that it already worked the way you're requesting. I remember [implementing this behaviour for Nuncabola](http://neverforum.com/fmpbo/viewtopic.php?pid=27684#p27684), but perhaps that wasn't in response to equivalent functionality in Neverball.

**Comment by afontenot** [comment]
Strange, that definitely isn't the way it works now, but maybe the check was lost in a refactor since then. The relevant bit of the code is https://github.com/Neverball/neverball/blob/master/ball/main.c#L160

        else if (config_tst_d(CONFIG_KEY_LEFT, c))
            st_stick(config_get_d(CONFIG_JOYSTICK_AXIS_X0), 0);
        else if (config_tst_d(CONFIG_KEY_RIGHT, c))
            st_stick(config_get_d(CONFIG_JOYSTICK_AXIS_X0), 0);

An SDL_KEYUP event on either the right or left arrow resets the axis to 0. So far as I can tell, there's no attempt in st_stick() to check that the released key is the active one.

**Comment by afontenot** [comment]
Looking at your forum post, you reference this commit: https://github.com/Neverball/neverball/commit/149a6aeded16d1c3ff9092c9ab2f22597365998f#diff-1784bfe7a2b77113627b30d8fa767627

But it looks like that one was intended to affect the view rotation keys, not the board-tilting arrow keys.

**Comment by parasti** [comment]
Yes, I never implemented that.

And I would have gotten away with it too if it weren't for you meddling kids.

**Comment by afontenot** [comment]
Is there anything I can do to help implement it?

**Comment by parasti** [comment]
The best help is getting your hands dirty and doing it yourself. For real. Even if you submit the worst patch the world has ever seen, it would serve as a motivator and a boost for us to see it through.

**Comment by afontenot** [comment]
Done; I don't know if my patch follows the same patterns as the rest of the code, but it does work.
