### ISSUE TITLE
Logo - My contributions to Neverball project

### ISSUE THREAD

**Issue by foways** [Neverball/neverball#164]
![web](https://user-images.githubusercontent.com/38687140/40272656-f7b6ba44-5bda-11e8-8f4b-d669d57e19ef.png)

Hello! I am a graphic designer, for the project "Neverball" I contribute a logo that I have designed is perfect, clean and minimalist.

The concept of logo design, I picked up a very easy symbol to remember that is "N" which is a spelling rather than "Never", And a symbol rather than a "ball". Here is the final result:

![last risult](https://user-images.githubusercontent.com/38687140/40272657-01d5e388-5bdb-11e8-8625-84b075f0f5ad.png)

![vrsi latar](https://user-images.githubusercontent.com/38687140/40272660-084422a2-5bdb-11e8-80d8-8e15289c8e28.png)

That's some of my contribution to "Neverball" hopefully you are interested and can use on your project. Give Feedback to me, and you can also give suggestions.

k-syusteem

**Comment by parasti** [comment]
Hi,

I appreciate your contribution, but I think we're very happy with the "ball". Letter logos work best for umbrella projects/businesses like G for Google and K for KDE. These entities do so many different things that a neutral letter logo works for them. But Neverball is a ball game. You roll around with the ball, collecting coins overcoming obstacles. The ball is the player character. It seems unlikely that any Neverball logo would ever steer away from the concept of a ball.

That said, your logo reminds me of Cheeseball (a ball in the game). I think it might be fun to turn this into a 3D ball model.

**Comment by k-syusteem** [comment]
Hi @parasti 
So, may I redesign it the way you want it?
