### ISSUE TITLE
Can't control ball using laptop accelerometer anymore

### ISSUE THREAD

**Issue by xCuri0** [Neverball/neverball#169]
I used to be able to do this with the version included with Ubuntu 14.04 but now I can't

**Comment by parasti** [comment]
The only reason why this might have worked (that I can think of) might be because the Linux kernel exposed the accelerometer as a joystick device and Neverball used it. Maybe? I don't believe there is anything we can do on our end that would restore that behavior.

**Comment by qwertychouskie** [comment]
I'm pretty sure this was probably a kernel change, or a change in SDL2's device blacklist.  SuperTuxKart had to blacklist some various laptop internal sensors from acting as gamepads, SDL probably has a similar blacklist.

**Comment by dsd** [comment]
See https://bugzilla.libsdl.org/show_bug.cgi?id=4789 for more info and a likely fix.

**Comment by AnterCreeper** [comment]
Why not use iio-sensor-proxy to read data from gyrometer and accelerometer, and use them to control game?
