### ISSUE TITLE
Swedish translation finished

### ISSUE THREAD

**Issue by jony0008** [Neverball/neverball#174]
Please update the Swedish localization for the next release. I have finished the translation on Transifex.

**Comment by parasti** [comment]
Resolved via #176

**Comment by jony0008** [comment]
@parasti This issue was not resolved via #176 because Swedish localization was not added. Please update the Swedish localization for the next release.

**Comment by parasti** [comment]
Oops.

**Comment by jony0008** [comment]
Please pull #179
