### ISSUE TITLE
Checkpoints were installed using Eclipse C Developers

### ISSUE THREAD

**Issue by ersohnstyne** [Neverball/neverball#181]
@rlk, the checkpoints were installed with using Eclipse C Developers.

The following methods and variables were added in the files:
- [checkpoints.c](https://github.com/ersohnstyne/neverball-premium/blob/master/ball/checkpoints.c): Full scripts
- [game_server.c](https://github.com/ersohnstyne/neverball-premium/blob/master/ball/game_server.c): Line 437
- [st_fail.c](https://github.com/ersohnstyne/neverball-premium/blob/master/ball/st_fail.c): Line 79
- [st_goal.c](https://github.com/ersohnstyne/neverball-premium/blob/master/ball/st_goal.c): Line 253
- [st_pause.c](https://github.com/ersohnstyne/neverball-premium/blob/master/ball/st_pause.c): Line 56

If the checkpoint was activated, it will save the progression data. And if the ball falls, it will return to the last position (...still working after timer runs out).
So, the youtuber PlayWithMahWii said (3:26 - 3:28): "[...so if you die, you will respawn here.](https://youtu.be/N7GDIZluYOU?t=197)"

**Comment by rlk** [comment]
1. Explain what the issue is. "Checkpoints were installed using Eclipse C Developers" doesn't describe a problem. What needs to be done?

2. Don't blanket @ our community. This only angers people and makes them want to ignore you.

**Comment by ersohnstyne** [comment]
**In this case, we need some entities like an structures in solid base:**
`struct b_chkp { float p[3]; float r; }`

**...which includes:**
Load Methods: `static void sol_load_chkp(fs_file fin, struct b_chkp *cp) { get_array(fin, cp->p, 3); cp->r = get_float(fin); }`
sol_load_indx(fs_file, struct s_base): `fp->cc = get_index(fin);`
sol_load_file(fs_file, struct s_base): `if (fp->cc) fp->cv = (struct b_chkp *) calloc(fp->cc, sizeof (*fp->cv)); for (i = 0; i < fp->cc; i++) sol_load_chkp(fin, fp->cv + i);`
sol_free_base(struct s_base): `if (fp->cv) free(fp->cv);`
Save Methods: `static void sol_stor_chkp(fs_file fout, struct b_chkp *cp)
{ put_array(fout, cp->p, 3); put_float(fout, cp->r); }`

**Comment by parasti** [comment]
Please use pull requests if you want to add a feature to the game.

**Comment by rlk** [comment]
And don't edit your comments to try to cover your tracks. Be honest.

**Comment by ersohnstyne** [comment]
I would leave my premium repository here, because the commits is too big.
I'll try into the beta version.

**Comment by ersohnstyne** [comment]
[Look here](https://github.com/Neverball/neverball/pull/186), what I have made it.
