### ISSUE TITLE
Add SFX for Albatross, Condor, Ostrich (NeverTrac #163)

### ISSUE THREAD

**Issue by Cheeseness** [Neverball/neverball#19]
This issue has been migrated from the Neverball Trac ticket list.

There could be new sound effects for when a player gets a Albatross (-3), a Condor (-4), or an Ostrich (-5) in Neverputt.

Granted, a Condor, or even an Ostrich, would be extremely rare when not complemented with a hole-in-one, but it may still be a nice touch-up for Neverputt.

Original ticket created by @ChallengeSY

**Comment by ChallengeSY** [comment]
I have been debating this ticket for several months. In the end, I have decided that this breaks consistency, not to mention adds needless complexity.

Thus, I no longer feel this enhancement is worthy. Since this was originally my idea, I will be resolving this issue by closing it.
