### ISSUE TITLE
How to rebuild version.h from version.in.h?

### ISSUE THREAD

**Issue by Begasus** [Neverball/neverball#190]
Trying a build for Haiku on the latest source checkout, a few files fail to not finding version.h?

**Comment by parasti** [comment]
Copy version.in.h to version.h and put anything you want in there. It's not an important file.

**Comment by Begasus** [comment]
Ok, thanks for the reply, atm I was able to build and run it :) 
https://ibb.co/gRZ8msz

**Comment by parasti** [comment]
Very cool!

**Comment by Begasus** [comment]
Neverputt also working :) https://ibb.co/album/fgvxTv
Created a PR at our haikuports tree for this, will see if I can cook something up to add support for Haiku here (no need for the patch then) :) https://github.com/haikuports/haikuports/pull/3919
