### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by AsciiWolf** [Neverball/neverball#193]
Please, consider supporting [Flatpak](https://flatpak.org), the modern cross-distro package distribution technology, and releasing Neverball (and Neverputt) on [Flathub](https://flathub.org).

**Comment by idoric** [comment]
I see three interests there. This would allow Neverball to be installed on small linux distributions without having to multiply packaging efforts. With Fedora Silverblue, the principle of operation and the interest of such a distribution calls for installing Neverball by the normal means (flatpak), and not the backup means (overlay). This also makes it easy to install Neverball for yourself if you are not the admin of the computer.

**Comment by parasti** [comment]
I have no first hand interest in this, so the patch would have to come from the Flatpak-using crowd.

**Comment by AsciiWolf** [comment]
@parasti I have made a Neverball Flatpak, it is currently [available here](https://github.com/flathub/flathub/pull/2055) and hopefully will soon be added to Flathub. Please, let us know whether you are interested in having push rights to the Neverball Flatpak Git repository once it is on Flathub. Thanks!

**Comment by parasti** [comment]
Very cool! The more people can play Neverball, the better.

How do updates work? Do flatpaks get built automatically (from Git tags, perhaps?) or is it always a manual process?

I honestly haven't used Linux for a good bit, so I'm not that interested in taking part here, but would be nice if this got updated as the game keeps changing.

**Comment by AsciiWolf** [comment]
In most cases, updating a Flathub Flatpak application is only a matter of pushing a new commit that updates the source archive/Git repo application version and version information in AppStream metadata (if this is not handled by upstream). The Flathub buildbot will automatically take care of the rest. :-)

**Comment by AsciiWolf** [comment]
Here is an example: https://github.com/flathub/net.supertuxkart.SuperTuxKart/commit/c2d6c1f302ea81ba1d561ff220979cee40cf7f19

**Comment by parasti** [comment]
I assume this is good to close.

https://flathub.org/apps/details/org.neverball.Neverball
