### ISSUE TITLE
Crash due to null pointer in `SAFECPY` call from fs_stdio, on platforms without `main` arguments

### ISSUE THREAD

**Issue by JayFoxRox** [Neverball/neverball#195]
C11 (free draft: http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1570.pdf) section "5.1.2.2.1  Program  startup", allows `argc` to be 0. In that case, `argv[0]` will be a null pointer.

This pointer is used to set the base directory using `fs_init(argv[0])`. 
This behavior is found in ball/main.c, putt/main.c and share/mapc.c.

However, in `fs_init` (share/fs_stdio.c), this null pointer is passed to `dir_name` (share/common.c); that function then calls `SAFECPY` (share/common.h), a macro around `strncpy`, which is potentially causing problems by reading from the null pointer.

*(The PhysFS backend's `fs_init` (share/fs_physfs.c) is probably not affected, because `PHYSFS_init` explicitly supports null pointers)*

---

To avoid this potential error, `fs_init` (share/fs_stdio.c) must handle the null pointer (it could fall back to "." as base directory), or the retrieval of `argv[0]` has to be extended to handle this case.

*(This issue was found during code review - however, I also did reproduce it by manually forcing `argv[0]` to `NULL` on my development system. I'm currently porting Neverball to another platform, and our libc will call `main(0, {NULL})`, so this case would occur then)*

**Comment by parasti** [comment]
Ah, the irony of naming something "SAFE". (I named it.)

Did you know also that SAFECPY causes warnings on modern GCC?

Thanks for the report, will try to fix as time permits.
