### ISSUE TITLE
Incompatible methods „log_printf“ in „base_config.c“

### ISSUE THREAD

**Issue by ersohnstyne** [Neverball/neverball#196]
The methods „log_printf“ in „base_config.c“ , that have been written into this code, is not allowed. To do this, simply remove the created log method line, before compiling again.

**Comment by fwp** [comment]
There's nothing wrong with using logging functionality in _base_config_. The makefile just needed to be updated further. Commit 0ec501d98c5d941af55a7fbff780c668adf66602 does this.

Closing.
