### ISSUE TITLE
Exclude detail lumps from node tree

### ISSUE THREAD

**Issue by fwp** [Neverball/neverball#205]
The node tree (_b_node_ struct) is only used for collision detection. By definition, detail lumps do not participate in collisions. It would therefore make sense not to include such lumps when creating the BSP trees in mapc. This would likely result in fewer and/or more balanced nodes.

In the early days of Neverball, the difference may have been negligible because only few lumps were marked as detail, like those for arrows or the goal texture. However, some newer levels have a very high detail-to-structural ratio. For example, _map-fwp/discs.map_ contains 1537 lumps, only 126 of which are structural.

**Comment by fwp** [comment]
There's also the question whether detail brushes (in Radiant terminology) need to be represented as lumps in the SOL at all. Bodies _(b_body)_ are already capable of containing arbitrary _b_geom_ data in order to support OBJ models.

**Comment by parasti** [comment]
The only downsides I can see for that second suggestion would be out-there stuff like object picking and SOL decompilation, neither of which exist in any form currently.

**Comment by fwp** [comment]
I had to look up what object picking is, just to be sure. From what I understand it's about identifying which object is at a given point in a rendered scene? One could think of a fancy inspection mode in Neverball that lets you click on the screen and then highlights the respective lump. Being able to decompile a SOL (and get useful results) is a good point, too. It may be worth, then, not to dissolve detail lumps into mere geoms, even if that would save a couple of bytes.

**Comment by fwp** [comment]
Nice! The total SOL size in the _data_ folder has decreased by 71 KB.

**Comment by ersohnstyne** [comment]
Remember for the deadline!: On 20th June 2020 will **moved up the ball by 1 radiant units**, which you do not meet the new specifications! This source code can be found at:
https://drive.google.com/file/d/1UMcHvGf8hRMBxxhChPteaYRcTKnj5L_S/view?usp=sharing
