### ISSUE TITLE
Neverball does not have window decorations on Wayland

### ISSUE THREAD

**Issue by AsciiWolf** [Neverball/neverball#223]
I have noticed this when working on the [Neverball Flatpak](https://github.com/flathub/flathub/pull/2055). The game window is displayed without any decorations (title bar ...) when running on Wayland:

![Neverball on Wayland](https://user-images.githubusercontent.com/2339930/104812734-863a1900-5804-11eb-857b-37497c3c0fd7.png)

**Comment by parasti** [comment]
Some people have discussed this here: https://github.com/dosbox-staging/dosbox-staging/issues/650

I don't think we need to do anything. Personally, it seems insane to me that Wayland is getting pushed so hard for so many years while they're still solving problems like this. It's funny, but also insane.

**Comment by AsciiWolf** [comment]
Well, it works fine by using XWayland (XServer running under Wayland) after removing the Wayland socket from Flatpak manifest. :-)

**Comment by parasti** [comment]
Should be fixed by SDL.
