### ISSUE TITLE
Error building module in PR #229 for Travis CI

### ISSUE THREAD

**Issue by ersohnstyne** [Neverball/neverball#231]
There was an error during building for Travis CI, maybe check your compilation (check your libraries on your makefile)!

**Comment by ersohnstyne** [comment]
If still an compilation errors, get in there!:
https://drive.google.com/file/d/1UMcHvGf8hRMBxxhChPteaYRcTKnj5L_S/view?usp=sharing

**Comment by parasti** [comment]
Fixed.
