### ISSUE TITLE
i18n release?

### ISSUE THREAD

**Issue by gunchleoc** [Neverball/neverball#239]
We have had a number of new locales finish their translations throughout the years.

Any idea how long it will take to get a new version out? Might it be worth the effort to make an i18n release of the last stable version?

**Comment by parasti** [comment]
That's an interesting proposition.

I haven't been keeping up with Transifex progress, so I'm not sure how up to date the source strings are. Do they align with the most recent release of Neverball?

Releasing an translations-only update would be much easier than an entirely new release that would require finishing up a lot of stuff.

**Comment by gunchleoc** [comment]
I have never run `tx push`, so they probably should still be on the last release version. You could run `tx push` from the last release's commit hash just to make sure.

**Comment by ersohnstyne** [comment]
Indonesian translation is now written! **Update your project from the TRANSIFEX to update your repository!**

**Comment by vancha** [comment]
Hey there! :) The translations for the Frisian language(language code fy)  has just been completed on transifex. I hope this can be included into the officlal project. Thank you in advance :)

**Comment by jorgesumle** [comment]
The POT file should be updated (there are 68 new strings) and translators should also update their translations.

By the way, I installed the game from source and I get "menu^Jogar" strings when I open the game (see image below). Can I do something to fix that? Is that `game^` part used to provide context? If that's the case, maybe you should consider using the [pgettext](https://www.gnu.org/software/gettext/manual/html_node/Contexts.html) function.

![Captura de ecrã de 2023-10-04 10-27-03](https://github.com/Neverball/neverball/assets/14212780/41eddc42-30cc-4dd3-9f01-bf411d07c53e)

**Comment by parasti** [comment]
Right now we're closer to the next release than doing this.
