### ISSUE TITLE
Can’t Sign in on the Neverforum

### ISSUE THREAD

**Issue by KodeBreaker-Has-SWAG** [Neverball/neverball#240]
There’s been an issue for around a month where users can’t sign in on the Neverforum. What happens is when I login into my account a message shows up saying I need to enable cookies for the site to login; even though I always have them enabled. I tried everything and still have the message popping up preventing me to login. I thought I was the only one with the problem so I went onto the Neverball Discord about the issue and everyone else on the server is having the same problem.

**Comment by parasti** [comment]
That sucks. Vidski (the person who owns the server) doesn't seem to be around much. I've tried to offer help, but no luck so far.

**Comment by ersohnstyne** [comment]
***IMPORTANT!:*** We had been moved into the Discord, so it will be used with desktop and mobile version. Just invite the link individually: **Nevercord:** https://discord.gg/PHzq2bz; **Nevercord II: https://discord.gg/kmtnB3kHEn**

**Comment by SVNMaster** [comment]
Same. I can't also sign in

**Comment by clementtttttttt** [comment]
rip neverforum, it's essentially dead now

**Comment by KodeBreaker-Has-SWAG** [comment]
I know this is pretty late saying this, but to everyone who wants to interact with the Neverball community can join the Neverball Discord server.

A good chunk of neverforum users are the server, here is the link:
https://discord.gg/HWp2kVQA

**Comment by ersohnstyne** [comment]
Neverball Discord server's entrance link is unlimited. The new entrance discord server is now limited of a time:
https://github.com/Neverball/neverball/issues/247

**Comment by qwertychouskie** [comment]
@AFCMS Here's a link that won't expire: https://discord.gg/U6dKHdnq8D
