### ISSUE TITLE
Octocat is not free

### ISSUE THREAD

**Issue by Wuzzy2** [Neverball/neverball#242]
Neverball is technically not FOSS because it includes the Octocat (the GitHub mascot) as a ball.

The fact that Neverball got a special permission to use the Octocat in Neverball (<https://github.com/Neverball/neverball/blob/master/doc/legal/license-octocat.md>) does not make it free, because this special permission doesn't extend to the players. Therefore, the players lack freedoms 2 and 3. They would not be able to e.g. fork Neverball since they do NOT have GitHub's permission to use Octocat.

There are 3 possibilities to solve this problem:
1) Octocat is released by GitHub as fully free media with no restrictions or only FOSS-compatible restrictions
2) Octocat is removed from Neverball
3) Admit that Neverball is no longer FOSS

Ideal would be solution number 1, but I doubt it will happen. Solution number 2 is the most realistic one. I really dislike solution number 3, that Neverball remains technically non-free only because of a single ball.

I suggest to remove Octocat from Neverball to ensure Neverball's FOSS status.

Thanks for reading. :-)

**Comment by Wuzzy2** [comment]
Leaving the legal stuff aside for a second: I also think it is strange to include Octocat in a free software in the first place, even if there would be no legal problem at all (which I doubt).

Octocat is the mascot of GitHub, and GitHub itself is a *proprietary* platform (via proprietary JavaScript code). It just doesn't make sense to me to include any symbolism of proprietary software in a game that is meant to be free, unless for satire. You also wouldn't like to include a Windows mascot (if there were one) or the Apple logo for the same reason, right?

BTW: Please don't interpret my issue as an attack on Neverball. It's not. I just care about ensuring software freedom for everyone, and this means looking at the seemingly small unimportant details at all.

**Comment by parasti** [comment]
Octocat ball was created by @Cheeseness to celebrate our move to Github. It marks a special occasion in Neverball history.

Hypothetically, if Neverball were to gain, e.g., a Windows port, a celebratory ball skin with the Windows logo would make perfect sense. Provided we could include it legally.

Yes, "Octocat is not free", but Octocat ball is not "software" It is a game asset. Neverball assets and software are completely decoupled. A non-free asset does not make the other assets or the Neverball software non-free. It's just a single non-free asset.

Here's option 4: delete the Octocat ball skin from your copy of the game. You don't even have to recompile, because the game doesn't care about Octocat ball. Only we care about it.

**Comment by parasti** [comment]
I should point out, for the record, that the status of Octocat ball is explicitly mentioned in LICENSE.md. It is neither hidden nor misrepresented.

**Comment by Wuzzy2** [comment]
To the player, it makes no difference if "assets" and the game code are decoupled on a technical level. It's the end result that matters. Since the Octocat is shipped in all public releases of Neverball that I'm aware of, I'd say the Octocat is absolutely part of the game. That's like saying the levels aren't part of Neverball since they are not code.
This distinction between "assets" and code in that some people do never made sense to me, esepecially for games. Since for a game, you need both. Remove the "assets" and you have no playable game, only an empty shell of a game. That doesn't really count.
Thus, if the "assets" of a game are not free, but only the code, then the game as a whole is not free either. This is the case even if it's only a single file.
So yeah, I don't deny the rest of Neverball if free/libre. But currently, the entirety of Neverball, the whole game (code+"assets") isn't. That's just a fact.

To be clear: The only thing that prevents Neverball from being fully free software seems to be the Octocat. Everything else seems fine. If Octocat wouldn't be there, Neverball would be fully free. Or someone *somehow* manages to convince GitHub to waive all their restrictive rights to the Octocat, i.e. that the permission doesn't only apply to the Neverball project, but to everyone. That's the whole point of free software, after all. Good luck with that … :-( If GitHub wouldn't be so restrictive, then this issue would not exist.

Now the real question seems to be whether you want Neverball to be free software in the first place. If yes, then sorry, there's unfortunately no way around the Octocat problem, it's just a fact that the presence of Octocat currently makes Neverball (as a whole) non-free.

But if you actually do not care about Neverball's status as free/libre software, then there's nothing else I can say.

**Comment by parasti** [comment]
The end result that you are arguing for is the removal of a cute, high-quality ball skin that a Neverball community member made to celebrate a milestone. If this is what is necessary for Neverball to become "free as in freedom" (based on what you have said), then I'm going to have to pass.

If you strongly feel otherwise, just delete the Octocat ball skin from your hard drive to obtain a "free as in freedom" Neverball.

**Comment by Wuzzy2** [comment]
Small correction: What I call "free as in freedom" is not just based on "what I have said", but it is based on what the official Free Software Definition (from FSF) and Open Source Definition (from OSI), both widely recognized as THE definitions of the terms "free software" and "open source" in the community. Just to make clear the meaning of those terms isn't just my personal opinion.

It is unfortunate that you ultimately rejected this issue, but since this decision seems to be final, I have nothing more to add. Have a nice day.

**Comment by parasti** [comment]
Just to be clear: I know all about the FSF definition of free software. I am a firm believer in software freedom being a net good for humanity. I've used Debian and Fedora for close to 20 years. I discovered Neverball via Linux. I learned C via Neverball. Without the free software license (GPL) that Neverball is licensed under, I literally would not be here, maintaining Neverball 16 years later.

What I don't agree with is your stated opinion about Octocat ball being a problem for Neverball and/or the free software movement.

**Comment by qwertychouskie** [comment]
This and #243 are good arguments for a full-featured addons system like SuperTuxKart has, you can side-step these kinds of issues completely, while also encouraging more people to create new content.

I'm willing to help implement such a system if there's interest ;)
