### ISSUE TITLE
Rename "rift" ball?

### ISSUE THREAD

**Issue by Wuzzy2** [Neverball/neverball#243]
This issue is more an opinion than anything else. Feel free to close if you disagree. ;-)

I don't like how the 'rift' ball is basically an advertisement for a real-world product, namely, the Oculus Rift. I don't know if this is an intentional advertisement or it was done simply because someone thought it would be fun. Probably the latter.

The ball looks nice, but I would like it more if it would not be such an explicit reference to a real-world product.

Here's what I suggest:

* Rename the ball to "vr" (=virtual reality)
* Remove or replace the written text "Oculus" written on the "headband". Either remove this text entirely or use some other word, maybe a fantasy product name, or "VR" or something else, as long it's not an obvious reference to a real-world product.

**Comment by parasti** [comment]
But it _is_ a direct reference to Oculus Rift.

See this video: https://youtu.be/bQqK2YuP2Tc

If you want a generic VR skin, make one!
