### ISSUE TITLE
License is misleading and (kinda) contradicts itself

### ISSUE THREAD

**Issue by Wuzzy2** [Neverball/neverball#244]
The website claims that Neverball is GPLv2 here at <https://neverball.org/download.php>:

> Neverball is released under the GNU GPLv2 (or a later version at your option).

This is technically not entirely true, or at the very least, it's misleading since Neverball contains the Octocat, which is proprietary and not released under the GPLv2.
(Note: This issue is NOT about whether it is right that Octocat is in the game. This time, it's only about the license info.)

The fact that media files and the code are technically separated doesn't matter from the user perspective. The ZIP file on the download page contains both bundled, and this is what the people will get as Neverball. For the user, this technical separation is basically non-existent.

The file `LICENSE.md` is a little bit better, but the fact that Octocat is **proprietary** isn't obvious at all. One has to be well-versed in law to notice this could be a problem. It also states the same as the download page:

> Neverball is released under the terms of the GNU General Public License version 2 or a later version (at your option).

Again this is only partially true / misleading. This statement is even directly contradicted by later statements, so the license file basically contradicts itself.

So, what you actually seem to mean is that the *code* of Neverball is GPLv2, while other parts are under difference licenses or no license at all (Octocat).

The current wording can be read as if Neverball *as a whole* is GPLv2. For people who rely on FOSS, this can be a stumbling block because they could accidentally and illegally distribute Neverball and make themselves vulnerable to lawsuits when they distribute Neverball on the Internet, falsely believing that Neverball is actually libre, since they techically never had permission to share Octocat (since it isn't that clear that sharing Octocat might be illegal).

For example, all Linux distributions that distribute Neverball could be sued because of Octocat, since those never got permission.

Please:

* Make a clear and explicit distinction between code and non-code in licensing information (e.g. instead of saying: “Neverball is licensed XYZ“, say: “The code of Neverball is …” and “The media files of Neverball are …”).
* Avoid making claims about the overall licensing of Neverball, it seems it's currently impossible that all of Neverball is under a single license
* Make it explicitly clear that the user is NOT allowed to share the Octocat with others, that the special permission from GitHub ONLY applies to the Neverball project and NOT the user, and that thus, if the user shares Neverball with the world, it will be infringement. This is the major "trap" in the Neverball license that I am concerned about
* Explicitly mention that Neverball, as a whole, is NOT free software / open source. It's easy to fall into this trap if you're not hyper-aware

----

Q: Why am I posting this issue?
A: Because I want to protect users into misinterpreting the license into falsely believing they can freely share and modify Neverball without getting sued (which is the whole point of FOSS btw). I am not posting this just to annoy you or say that you are bad people. :-)

**Comment by parasti** [comment]
Neverball is licensed under GPLv2+.

Octocat logo is used within Github guidelines with written permission from Github.

The issue description is so overcomplicated that it borders on nonsensical.

Feel free to reopen only if you are a lawyer or planning to distribute Neverball in a manner tha doesn't align with the dozens of existing distros that don't have this problem (including the very license-cautious Debian).
