### ISSUE TITLE
Ray tracing for neverball

### ISSUE THREAD

**Issue by ghost** [Neverball/neverball#277]
I lost all my ability and skills for made it. I needs some your helps. I prefer to see results both for Neverball and Nuncabola remake.

**Comment by parasti** [comment]
I prefer this, too. Would it be cool - yes. Do I think a Github issue is required - honestly, no. I will probably close this in 365 days.

**Comment by unit-a-user** [comment]
I have plans to try implement it... but needs to make some C wrappers for graphics library.

**Comment by germe-deb** [comment]
OK this is strange. Ray Tracing in neverball? XD?
neverball is a game with a static lighting, and raytracing can be obtrussing in areas where there are platforms in top, as they will produce shadow.
I think ray tracing is a bit unnecessary

**Comment by camthesaxman** [comment]
Would a tool like Reshade not suffice for enhancing your graphics? While ray traced Neverball would be neat, I don't think there is enough demand for us to write a new ray traced renderer for it.

**Comment by unit-a-user** [comment]
Not reshade, I think about partial replacement rendering.
