### ISSUE TITLE
Support for switching between windowed and full screen at runtime

### ISSUE THREAD

**Issue by camthesaxman** [Neverball/neverball#289]
I think it would be a nice feature to be able to swap between full screen and windowed while in game (Alt+Enter is a common keyboard shortcut for this). In windowed mode, the window can be resized, so why not extend that to full screen as well.

**Comment by parasti** [comment]
Try pressing F11.

**Comment by camthesaxman** [comment]
Sorry, didn't realize this was already a feature.
