### ISSUE TITLE
Moving the camera with the gamepad stick locks the game into manual camera mode

### ISSUE THREAD

**Issue by camthesaxman** [Neverball/neverball#290]
As I understand it, the camera can be rotated in one of three ways:
* The left and right mouse buttons
* The L1 and R1 buttons on the gamepad
* The X axis of the gamepad's second stick 
When using the first two methods, after releasing the button, the camera will gradually return to its normal position as the ball moves (as long as you are not in manual camera mode). However, the third method using the stick to move the camera does not behave this way. If you move that stick at all, the camera will behave as if it was in manual camera mode, even if the camera isn't actually in manual mode.

#### Expected behavior:
After releasing the right stick (while in Chase or Lazy mode), the camera should return to its default position as the ball moves, just as how it does when using the mouse buttons or L1/R1 buttons.

#### Actual behavior:
After releasing the right stick (while in Chase or Lazy mode), the camera stays in that position and behaves like manual camera mode. Pressing the mouse buttons or L1/R1 buttons will return the camera to normal.

#### Steps to reproduce:
1. Connect a gamepad and start up the game.
2. Go into the options and make sure all of your gamepad controls are set appropriately.
3. Enter a level and make sure you are in Chase or Lazy camera mode (not Manual).
4. With the ball in motion, move the camera using the right stick and release. The camera will not return to its default position as the ball moves.

**Comment by parasti** [comment]
I don't have this problem, so I need more info.

There is a feature for the mouse where pressing both buttons at the same time enables manual mode temporarily. Do you see a possible interaction here?

Can you reproduce this on https://neverball.github.io/? Are all the axes configured as well?

**Comment by jfbauer432** [comment]
This sounds like this bug that I reported against Ubuntu some time back
https://bugs.launchpad.net/ubuntu/+source/neverball/+bug/1939725 (I filed this with Ubuntu as it worked as expected on Ubuntu 20.04 but not in Ubuntu 21.04 (or later versions up to at least 22.04), and the version of neverball had not changed.

And it does *not* reproduce on https://neverball.github.io/
