### ISSUE TITLE
Support for moving goals and items

### ISSUE THREAD

**Issue by Adacrop-The-Great** [Neverball/neverball#327]
An interesting feature that should be implemented in Neverball is giving items (coins, grow/shrink, and clocks) and goals the ability to be connected to a path (target and target2), like bodies (func_trains and misc_models). This will give mappers greater flexibility for level design and open up a new range of level ideas. Some mappers such as me and KodeBreaker have several level ideas featuring moving coins, so this feature should definitely be considered.

Any thoughts?

**Comment by KodeBreaker-Has-SWAG** [comment]
This would be a great addition to the game. It would make some really interesting levels.

**Comment by parasti** [comment]
Implemented since 1f632d9
