### ISSUE TITLE
Joystick input unsupported on desktop (1.6, Linux Mint)

### ISSUE THREAD

**Issue by applecuckoo** [Neverball/neverball#328]
Hi there, I wanted to try out Neverball with the Linux kernel's native support for Nintendo Switch controllers, and it seems that support only works on the web Emscripten version, and not the local 1.6 build served by both the Linux Mint repos and Flathub.

**Comment by applecuckoo** [comment]
Apologies, think this is a false alarm - I didn't read the [manual](https://github.com/Neverball/neverball/blob/master/doc/manual.txt).

**Comment by parasti** [comment]
Not sure what we should do here. Just use a newer Neverball from this repo. 1.6 turns 10 years old next year.

**Comment by qwertychouskie** [comment]
> Not sure what we should do here. Just use a newer Neverball from this repo. 1.6 turns 10 years old next year.

AFAIK there isn't any release newer than 1.6.0?  I know there are definitely improvements in Git, but without a new official release distros are never going to package the newer code.

**Comment by parasti** [comment]
Very true.

I wasn't saying there are newer tagged versions of Neverball. All I'm saying is there are improvements accumulated in this repo, among them improvements to joystick handling. The version published on neverball.github.io includes those improvements.

Any discussion on distros, tagged releases, etc., is fine, but that's not what I was talking about.
