### ISSUE TITLE
Package setting menu must be parented with game settings

### ISSUE THREAD

**Issue by ersohnstyne** [Neverball/neverball#334]
The package setting menu must be parented with game settings, not title menu.

**Comment by parasti** [comment]
I don't think so, but - why?

**Comment by parasti** [comment]
Why?

**Comment by ersohnstyne** [comment]
In package manager, you'll go into the game settings/options from the main menu, and then select "Manage" at "Packages".
https://1drv.ms/i/s!Airrmyu6L5eym1sf9elkkbTjmb9E?e=wdJL9Q

**Comment by parasti** [comment]
I understand that. I'd like to know why that is better than having a button on the main screen.
