### ISSUE TITLE
OpenGL Extensions: Fixed crashes

### ISSUE THREAD

**Issue by ersohnstyne** [Neverball/neverball#337]
If anyone else have an oldest laptop hardware, but trying to initialize OpenGL extensions, then they will print only the OpenGL logs and crashes during render, whenever wasn't associated:
* ARB_multitexture
* ARB_vertex_buffer_object
* ARB_point_parameters
* GREMEDY_string_marker (optional debugging)

Recommended fixes should be go in there:
[OpenGL extensions crash fixes](https://github.com/Neverball/neverball/pull/336)

**Comment by parasti** [comment]
This issue seems redundant.
