### ISSUE TITLE
git tag, so packagers live beyond 2014 

### ISSUE THREAD

**Issue by Arnaudv6** [Neverball/neverball#347]
Hi, and thanks for keeping this awesome game living.
Please consider tagging: this is a requirement for packagers to update their packages.
BR

**Comment by mooreye** [comment]
`added this to the Neverball 1.7.0 milestone`

What's the point if this milestone will never be tagged? 🤔

**Comment by parasti** [comment]
@mooreye Hi. If you want faster development, just  use the sponsor link. Thanks.

**Comment by parasti** [comment]
There are some prerelease tags now.

**Comment by Arnaudv6** [comment]
Great, thanks @parasti.
