### ISSUE TITLE
Neverputt - add the ability to manage levels with subdirs

### ISSUE THREAD

**Issue by brunetton** [Neverball/neverball#351]
## Problem description

As there is a hard limitation in Never**putt** for 7 custom levels sets max, users (like my father and some friends) regularly wants to make place for new levels, so removing some of currently added new levels and install new ones.

For this they have to quite deeply understand the internals of Neverputt; how to read and understand the `holes-*.txt` files (despite the fact that there's no doc available) to be able to remove the correct `map-*` dir. There are no naming conventions, that makes things complicated to follow. 

I spent many hours helping those players managing their Neverputt courses.

Example with the `puttworksgamma` holes levels. Imagine I managed to install those levels (as a non-dev this is not easy) and now I want to remove it. I have many other levels laying around on my Neverball dir. I can't easily find the corresponding files as:
- there's no `holes-puttworksgamma.txt`. The txt file is named `holes-csy.txt`
- there's no `map-puttworksgamma`, the map folder is named `map-csyp`

I do not talk about the screenshot as this is not a problem if it's laying around

## Proposed solution

It would be super simple for users if it could be possible to manage only directories: one directory = one level set

- to add a course: add the directory in Neverball dir
- to remove a course: remove the directory

Those courses dirs should be placed inside a `~/.neverball/courses/` dir 

This would then allow courses creators to name their files as they want, and users won't have to look inside txt files to find corresponding maps.

## Example

A Neverputt user dir would be like this:

```
~/.neverball
├── courses
│   ├── jumpcourse
│   │   └──  [Some files needed for Jump course, user do not need to worry about that]
│   └── puttworksgamma
│       └──  [Some files needed for Jump course, user do not need to worry about that]
├── neverballrc
├── neverputt.log
└── Screenshots
```

This won't break backwards compatibility as this would still be okay to place files directly in Neverputt dir for users that are used to.

What do you think of that ? I don't think this would be very hard to implement (I can try to do it by myself even if I didn't practiced C for years :no_mouth:

Thanks

**Comment by brunetton** [comment]
> Not sure why you're installing files manually when you can already do this:
> 
> * to install, put the ZIP file under ~/.neverball or Documents\My Games\Neverball
> * to uninstall, remove the ZIP file
> 
> This was implemented somewhere around 2009, so nearly all levels and courses released in the last 14 years are installable in this way.

Ow yes indeed, I forgot to mention: this doesn't works (in Linux, I didn't tried in Windows). Now you remind me that I read somewhere that it should be possible, but it doesn't works (Neverputt 1.6.0+git20180603-3 from Ubuntu).

**Comment by brunetton** [comment]
The content of the zip file in my test is:
- holes-jump.txt
- holes-jump/ that contains all maps and sol files

**Comment by parasti** [comment]
Write to Ubuntu developers to fix this, I guess.

They are using an unreleased version of Neverball from 2018 that did not have ZIP enabled by default (it defaulted to ENABLE_FS=stdio instead). That's really unfortunate.

Or just compile the newest code from Github yourself.

**Comment by brunetton** [comment]
Okay you're right, I'll address it to Ubuntu.
By the way I wonder why the zip option is not enabled by default. Limit the number of external libs ?

Anyway thanks !

**Comment by brunetton** [comment]
Here we go: https://bugs.launchpad.net/ubuntu/+source/neverball/+bug/2046807
