### ISSUE TITLE
Responsive resolution

### ISSUE THREAD

**Issue by mooreye** [Neverball/neverball#359]
If you fullscreen the game on a 4K monitor, it will be 2840x2160. Then, if you open the game on FullHD, the game will overscan instead of responsively changing res to 1080p.

If you had 1080p res and then use 4K monitor, it will scale down to 1/4 of screen size with the rest being black space.

**Comment by parasti** [comment]
Which version of the game? Where did you install it from?

**Comment by parasti** [comment]
I believe this is fixed in the dev version (here on Github and also at  https://play.neverball.org), which has resizable windows.
