### ISSUE TITLE
Certain fonts are blurry when in fullscreen on web build

### ISSUE THREAD

**Issue by Calinou** [Neverball/neverball#366]
- Related to https://github.com/Neverball/neverball/issues/280.

On https://play.neverball.org as of July 2024, fonts are occasionally blurry when in fullscreen **(click to view at full size to see a difference)**:

![image](https://github.com/Neverball/neverball/assets/180032/2e40e559-303c-4650-8e46-59334237a3a2)

Example in the addons page:

![image](https://github.com/Neverball/neverball/assets/180032/8bed5f9c-4566-426b-b625-454a83b5854e)

It's most noticeable on a 4K display but may occur at lower resolutions too. Interestingly, only certain lines of the message are blurry (e.g. the first and second lines of the level description in the first image). HUD elements are not affected by this issue.

I'm using Firefox 127 on Linux with a NVIDIA GPU.

Comparison at the default window size:

![image](https://github.com/Neverball/neverball/assets/180032/bdd43aa3-0687-4410-b8e1-b889754bd1d9)

**Comment by parasti** [comment]
Thanks, these are high quality reports.

I don't think this is related to that other issue. This looks like screen/texture misalignment. The other issue has to do with capability detection.
