### ISSUE TITLE
High audio latency on web build

### ISSUE THREAD

**Issue by Calinou** [Neverball/neverball#368]
On https://play.neverball.org as of July 2024, audio latency when doing anything (such as clicking in menus, collecting a coin or bumping into a surface) is quite high compared to the native version, or compared to other web games.

This is typically avoided by using the Web Audio API to handle audio playback[^1], so the game itself is no longer playing sounds, but only passing requests to the browser to play sound. In fact, I remember reading about SDL_mixer having a built-in integration for this (or was it OpenAL?).

[^1]: This is what Godot recently switched to for web builds in https://github.com/godotengine/godot/pull/91382.

There might be ways to mitigate this without a Web Audio implementation, such as using a lower audio buffer size. This has the risk of introducing audio cracking on slow CPUs, so this would need to be tested on low-end devices first.

Here it is in Firefox 127 on Linux (Fedora 40 with PipeWire):

https://github.com/Neverball/neverball/assets/180032/fd55af61-2c64-46a1-8423-19f9ae079aae

And Chromium 126 on Linux, where audio latency is slightly lower but still noticeable:

https://github.com/Neverball/neverball/assets/180032/014b521d-99c8-4321-a156-929206243141

**Comment by parasti** [comment]
Wrote some code to address this, check it out (it's already live on play.neverball.org - but maybe clear website data and hard refresh) [f80b0cd](https://github.com/Neverball/neverball/commit/f80b0cdeef7f26b3048875516acaaedbc889f2f5)
