### ISSUE TITLE
Translation access request

### ISSUE THREAD

**Issue by Noordfrees** [Neverball/neverball#383]
Hi,

I requested to translate Neverball into Low German (nds) on Transifex, and although the language appears to have been added, my request to join the Low German translation team on Transifex seems to have gone under.
So could you please give me access so I can translate this great project into Low German? :)

Best regards,
Benedikt Straub (Nordfriese on Tx)

**Comment by parasti** [comment]
Done, thanks for the reminder.

**Comment by Noordfrees** [comment]
Thank you :)
